training:
  max_epochs: 10
  workers: 8
  batch_size: 8
  gradient_accumulation_steps: 8
  weight_decay: 1e-1
  log_freq: 500
  eval_steps: 500
  mixed_precision: True
  max_lr: 2e-4
  min_lr: 2e-5
  warmup: 4000
  no_lr_decay: False
  steps: 48000
  anneal_steps: 45000
  resume_training: False
  training_checkpoint_file: 'checkpoints/training_params.pth.tar'
  log_to_aws: True
  prefix: 'GPT2_1B_optimized'
  n_devices: 8
  use_pretrained_weights: False

model:
  size: 'XL*'
  fused_residuals: True
  type: GPT2
  tied_weights: True
  num_head: 8
  ALiBi: True
  

data: 
  corpus: 'webtextnouveau'
  metadata_path: 'data/processed/train/openwebtext_metadata.json'
  train_shard_urls: ["data/processed/train/webtextplusplus_no_resample_train-{000000..000211}.tar.gz", "data/processed/train/WebTextNouveau_train-{000000..000050}.tar.gz"]
  validation_shard_urls: ["data/processed/train/webtextplusplus_no_resample_validation-{000000..000018}.tar.gz", "data/processed/train/WebTextNouveau_validation-{000000..000006}.tar.gz"]
  seq_len: 1024
  train_len: 512